### PR TITLE
View post comments

### PR DESCRIPTION
**Pull request by jamessushum**
# Description
- User is directed to comments list view when 'View Comments' button is clicked in specific post
- Comments are sorted by latest creation date/time with most recent appearing at the top
- Title of the post is displayed at the top of the page
- User is re-directed back to the post details view when 'Back to post' button is clicked
Ticket #19 : https://github.com/nss-day-cohort-41/tabloidmvc-the-gefilte-fish/issues/19
## Type of change
Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
# Testing Instructions
- Pull down branch and CD to branch files
- Run updated SQL 1.Create_DB and 2.Seed_Data scripts to add sample data in Comments table
- Run app with debugger or dotnet run
- Once logged-in navigate to Post link in navbar and select View on any available Post
- At bottom of Post details view, click 'View Comments' button, this should direct the user to the comments list view
- Comments should be displayed along with button to go back to post details
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by dLars99 — CHANGES_REQUESTED** [review]
Recommend changing "GetAllComments" to a name like "GetCommentsByPost," to help differentiate it from the other "GetAll" methods in the other repositories.

**Review by dLars99 — APPROVED** [review]
Looks good!

**Comment by johnhester** [comment]
Functionality works as described and naming issue has been resolve.

**Review by johnhester — APPROVED** [review]
👍

**Pull request merged**
