### PR TITLE
Aj post edit

### LINKED ISSUE #8: Edit a Post
As a author I would like to be able to modify my Posts so that I can correct mistakes or add additional content.

**Given** the user is viewing the Post list  
**When** they select the option to edit an Post  
**Then** the user should be directed to a form and given the ability to change the Post's information  

**Given** the user is finished updating the Post information  
**When** they click the `Save` button  
**Then** the updated Post should be saved to the database  
**And** the user should be redirected to the new Post's details page

**Given** the user has decided not to edit the Post  
**When** they click the `Cancel` button  
**Then** the user should be redirected back to the list page

Editable Information

* Title
* Content
* Category
* Header Image URL (optional)
* Publication Date (optional)

### PR DESCRIPTION
**Pull request by Adanieljohnson91**
# Description
Checked Functionality of 
-Create Post
-Post Details
Added Edit Functionality.
Added Delete.
Fixes #8 #7 #3 #6 #5 
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
# Testing Instructions
Check Edit by selecting a post and changing all input fields.
Delete is a two-part system. Hit the trashcan and you will be redirected.
Once at the followup page verify it is the correct post and confirm the delete.
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by johnhester — APPROVED** [review]
Functionality works as intended. All found bugs have been addressed.

**Review by dLars99 — CHANGES_REQUESTED** [review]
I'm still seeing the same behavior as before, where a brand new post without a publication date cannot be edited. I believe the GetPublishedPostById references in PostController need to be changed to GetPostById under Edit and Delete

**Comment by Adanieljohnson91** [comment]
Im not seeing the issue. I am able to create, immediately edit, and also edit any post that was previously created @dLars99; can you check again? or give your testing instructions.

**Comment by dLars99** [comment]
No problem. It's kind of an edge case that I stumbled on to.
1. Create a new post. Leave the publication date _blank._
2. After saving the post, click the edit or delete buttons.
3. The post info in Edit or Delete is blank. I believe this is because those methods in the controller are still utilizing GetPublishedPostById.

PostCreate
PostMade
BlankEdit
BlankDelete

**Comment by Adanieljohnson91** [comment]
Should of been fixed; I’ll check it out later...

Thank you, David!

**Review by dLars99 — APPROVED** [review]
It works!

**Pull request merged**
